<div style="background-color:#F0EFED ;color:#EB3D6B;padding:20px;border:1px solid #3184BB;text-align:center;">
<p style="text-align:center"><font size="14" color="#EB3D6B" face="Lora"><i>MagicBrics_data_collection</i></font> </p>
</div>

In [209]:
# Import Libraries
import requests
from bs4 import BeautifulSoup
import numpy as np
import pandas as pd
import re

In [149]:
# Code for the collection of the data
# here list of 4 cities are taken and collection of data is done for them
cities = ['bangalore','mumbai','chennai','visakhapatnam']
price=[]
per_sqt=[]
BHK=[]
Carpet_Area=[]
Owner=[]
Floor=[]
Area=[]
City=[]
for j in cities:
    url = "https://www.magicbricks.com/flats-in-"+j+"-for-sale-pppfs"
    print(url)
    page = requests.get(url)
    soup = BeautifulSoup(page.text)
    
    for i in soup.find_all("div",class_="mb-srp__card__price--amount"):
        price.append(i.text)
        
    for i in soup.find_all("div",class_="mb-srp__card__price--size"):
        per_sqt.append(i.text.split(' ')[0])
        
    for i in soup.find_all("h2",class_="mb-srp__card--title"):
        BHK.append(i.text[0])
        
    for i in soup.find_all("div",class_="mb-srp__card__summary--value"):
        a =i.text
        b = re.findall(r"(\d+)\ssqft",str(a))
        if b:
            Carpet_Area.append(b[0])
            
    for i in soup.find_all('div',class_='mb-srp__card__ads--name'):
        Owner.append(i.text.split(':')[1])
            
    for i in soup.find_all("div",class_="mb-srp__card__summary__list--item"):
        a = i.text
        b = re.findall(r"\w+\s\w+\s\w+\s\d+",a)
        if b:
            Floor.append(b[0])
            
    for i in soup.find_all("h2",class_="mb-srp__card--title"):
        Area.append(i.text.split('in')[1].split(',')[0])
        City.append(j)
    print(i,'---->', len(Owner))
    print(i,'---->', len(Floor))
    print(i,'---->', len(per_sqt))

https://www.magicbricks.com/flats-in-bangalore-for-sale-pppfs
<h2 class="mb-srp__card--title">2 BHK Flat for Sale in Yelahanka , Bangalore</h2> ----> 30
<h2 class="mb-srp__card--title">2 BHK Flat for Sale in Yelahanka , Bangalore</h2> ----> 30
<h2 class="mb-srp__card--title">2 BHK Flat for Sale in Yelahanka , Bangalore</h2> ----> 29
https://www.magicbricks.com/flats-in-mumbai-for-sale-pppfs
<h2 class="mb-srp__card--title">2 BHK Flat for Sale in Mulund West , Mumbai</h2> ----> 60
<h2 class="mb-srp__card--title">2 BHK Flat for Sale in Mulund West , Mumbai</h2> ----> 58
<h2 class="mb-srp__card--title">2 BHK Flat for Sale in Mulund West , Mumbai</h2> ----> 52
https://www.magicbricks.com/flats-in-chennai-for-sale-pppfs
<h2 class="mb-srp__card--title">2 BHK Flat for Sale in Chennai</h2> ----> 90
<h2 class="mb-srp__card--title">2 BHK Flat for Sale in Chennai</h2> ----> 88
<h2 class="mb-srp__card--title">2 BHK Flat for Sale in Chennai</h2> ----> 81
https://www.magicbricks.com/flats-in-visakhapatnam-for-sale-pppfs
<h2 class="mb-srp__card--title">2 BHK Flat for Sale in MVP Colony , Visakhapatnam</h2> ----> 120
<h2 class="mb-srp__card--title">2 BHK Flat for Sale in MVP Colony , Visakhapatnam</h2> ----> 118
<h2 class="mb-srp__card--title">2 BHK Flat for Sale in MVP Colony , Visakhapatnam</h2> ----> 110

In [159]:
# printing to see the values are obtained are not
print(price)
print(per_sqt)
print(BHK)
print(Carpet_Area)
print(Owner)
print(Floor)
print(Area)
print(City)

# Finding the length to see is all the lengths are same
print(len(price))
print(len(per_sqt))
print(len(BHK))
print(len(Carpet_Area))
print(len(Owner))
print(len(Floor))
print(len(Area))
print(len(City))

['₹60 Lac ', '₹80 Lac ', '₹48 Lac ', '₹1.35 Cr ', '₹61 Lac ', '₹1.30 Cr ', '₹50 Lac ', '₹1.80 Cr ', '₹1 Cr ', '₹1.02 Cr ', '₹1.45 Cr ', '₹3.85 Cr ', '₹70 Lac ', '₹85 Lac ', '₹98 Lac ', '₹60 Lac ', '₹78 Lac ', '₹57 Lac ', '₹1.08 Cr ', '₹57 Lac ', '₹35 Lac ', '₹1.80 Cr ', '₹2.75 Cr ', '₹1.12 Cr ', '₹1 Cr ', '₹1.45 Cr ', '₹80 Lac ', '₹1.35 Cr ', '₹2.10 Cr ', '₹51.2 Lac ', '₹73 Lac ', '₹22 Lac ', '₹2.25 Cr ', '₹2.70 Cr ', '₹41 Lac ', '₹5.99 Cr ', '₹1.20 Cr ', '₹1.30 Cr ', '₹65 Lac ', '₹3.75 Cr ', '₹2.70 Cr ', '₹1.02 Cr ', '₹95 Lac ', '₹60 Lac ', '₹15 Cr ', '₹32 Lac ', '₹98 Lac ', '₹4.89 Cr ', '₹44.9 Lac ', '₹70 Lac ', '₹1.05 Cr ', '₹30 Lac ', '₹1.25 Cr ', '₹1.90 Cr ', '₹1.55 Cr ', '₹1.28 Cr ', '₹2 Cr ', '₹2.52 Cr ', '₹1 Cr ', '₹1.60 Cr ', '₹55 Lac ', '₹80 Lac ', '₹60 Lac ', '₹60 Lac ', '₹85 Lac ', '₹49 Lac ', '₹55 Lac ', '₹53 Lac ', '₹69 Lac ', '₹1.25 Cr ', '₹87 Lac ', '₹32 Lac ', '₹71 Lac ', '₹85 Lac ', '₹47 Lac ', '₹46 Lac ', '₹43 Lac ', '₹1.15 Cr ', '₹27 Lac ', '₹29.7 Lac ', '₹59 Lac ', '₹45 Lac ', '₹35 Lac ', '₹74 Lac ', '₹39 Lac ', '₹46 Lac ', '₹1.30 Cr ', '₹40 Lac ', '₹70 Lac ', '₹74.9 Lac ', '₹47.5 Lac ', '₹72 Lac ', '₹97 Lac ', '₹63 Lac ', '₹35 Lac ', '₹63.6 Lac ', '₹47 Lac ', '₹1 Cr ', '₹38 Lac ', '₹30 Lac ', '₹97.5 Lac ', '₹30 Lac ', '₹30 Lac ', '₹55 Lac ', '₹60 Lac ', '₹73 Lac ', '₹45 Lac ', '₹89 Lac ', '₹70 Lac ', '₹49 Lac ', '₹43.6 Lac ', '₹56 Lac ', '₹97 Lac ', '₹47 Lac ', '₹78 Lac ', '₹38.9 Lac ', '₹26 Lac ', '₹42 Lac ', '₹38 Lac ', '₹78 Lac ']
['₹4950', '₹6957', '₹4528', '₹7542', '₹5706', '₹7303', '₹5000', '₹11335', '₹8889', '₹6997', '₹8146', '₹20632', '₹5655', '₹6071', '₹9800', '₹6367', '₹5158', '₹6374', '₹4553', '₹4545', '₹7500', '₹12500', '₹7705', '₹5305', '₹7436', '₹5333', '₹7418', '₹10194', '₹4650', '₹26471', '₹23276', '₹16667', nan, '₹23636', '₹37500', '₹27136', '₹18545', '₹60000', '₹5047', nan, '₹11529', '₹38459', '₹7242', nan, '₹10000', '₹14583', '₹5376', '₹12042', '₹13669', '₹19375', '₹21333', '₹33333', '₹22951', '₹10695', '₹25316', '₹5268', '₹8658', '₹5000', '₹4444', '₹8947', nan, '₹4895', '₹6111', '₹5268', '₹5712', '₹8367', '₹8406', nan, '₹5086', '₹9140', '₹6112', '₹7931', '₹4335', '₹11616', '₹4060', '₹3999', '₹7584', '₹5294', '₹6481', '₹6198', '₹4343', '₹6571', '₹11818', '₹5249', '₹6763', '₹8000', '₹3242', '₹5143', '₹4615', '₹4000', '₹4667', '₹4130', '₹4087', '₹7634', '₹3619', '₹3046', '₹7500', '₹5000', '₹3000', '₹3667', '₹3750', '₹4056', '₹3309', '₹5235', '₹4118', '₹3250', '₹6054', '₹5173', '₹4215', '₹4756', '₹3700', '₹2600', '₹4667', '₹4222', '₹7091', nan, nan, nan, nan, nan]
['3', '2', '2', '3', '2', '3', '2', '3', '3', '2', '3', '3', '3', '2', '2', '2', '2', '2', '3', '3', '2', '4', '3', '3', '3', '3', '3', '3', '3', '2', '1', '1', '2', '3', '1', '3', '2', '1', '1', '2', '2', '1', '1', '2', '4', '2', '2', '3', '1', '2', '1', '1', '2', '3', '2', '2', '1', '2', '2', '2', '2', '2', '3', '2', '2', '2', '3', '2', '3', '2', '2', '1', '2', '2', '2', '1', '2', '2', '1', '2', '2', '2', '1', '3', '2', '2', '2', '2', '2', '2', '3', '2', '3', '3', '2', '3', '2', '3', '2', '2', '3', '1', '2', '3', '3', '3', '3', '3', '3', '2', '2', '2', '3', '2', '3', '3', '2', '2', '2', '2']
['1000', '1150', '1060', '1790', '803', '1640', '1250', '1588', '1000', '1465', '1500', '1418', '1350', '1000', '1250', '857', '753', '1186', '1250', '770', '2150', '1900', '1460', '1885', '1950', '1250', '1820', '2060', '740', '331', '310', '610', '1160', '665', '1052', '685', '400', '332', '776', '800', '450', '430', '675', '1870', '820', '850', '1172', '404', '575', '507', '558', '680', '1130', '562', '535', '590', '792', '935', '632', '1044', '800', '1200', '1350', '950', '1001', '900', '800', '852', '1494', '700', '634', '1395', '930', '464', '580', '509', '990', '445', '469', '778', '850', '540', '1194', '898', '700', '600', '762', '1035', '800', '1300', '823', '1700', '1575', '700', '1540', '1150', '1310', '1000', '915', '1300', '600', '1000', '1300', '1516', '1800', '1100', '1620', '1600', '970', '1133', '925', '1875', '1050', '1640', '840', '800', '900', '650', '800', nan]
[' Omkar Pandey', ' gokul', ' Thayumanavan', ' Prasanna', ' Akash Akash', ' av nath', ' Sangeeta Pillai', ' ganga k', ' Anjan K', ' Omesh Saraf', ' Mohd Hussain ', ' Rahul Jain', ' Gaurav Kumar GAURAV', ' Ancy', ' Anoop', ' geetha', ' Omkar Omkar', ' ruchika', ' jeswanth', ' vikas saxena', ' Ranju', ' tezal', ' shravan', ' Bhav', ' Nagananda', ' MD Fuzail', ' ashwanth', ' Partha Sarma', ' Shekar', ' Sashank Constructions', ' K SH', ' NIYATI', ' Sachin Kunder', ' Motashaw Motashaw', ' MONCY BHASKAR', ' Anam khan', ' Milind Desai', ' Jas Baljeet J', ' Gangaram Dhuri', ' Satyajit Satyajit', ' vasant ahir', ' Rajendra', ' Aditi Shah', ' Haroon mansuri', ' kishor kishor', ' Medha Naik', ' Anita', ' jagdish Dassani', ' Raghav Sharma', ' nandan lanjekar', ' amit chalke', ' Arun Iyer', ' Ritu', ' Khuzema Tajir', ' Dipti solanki', ' sujatha', ' Aysha Khan', ' DHRUV SHARMA', ' Mumtaz Nazim', ' Savith Raghavan Savith Raghavan', ' Yogesh Baskaran', ' K VINODH KUMAR', ' GURURAJAN BABU', ' Vijay Jaya', ' siva', ' Prasanna', ' M DINESH KANNA', ' Elango Rajendran', ' Dev', ' vinothan', ' Owner', ' M G S Jayamalathi', ' Mahalingam', ' Kads', ' YOGEESWARAN', ' Kuppuswamy Bj', ' Jayalakshmi', ' Vidhya vidhya', ' Sujith', ' sakthi', ' Santhosh', ' Santhosh Developers', ' R Premalatha', ' Jebaselvan Navaraj', ' Ramkumar Gopalsamy', ' ram', ' Faizal', ' Vimal Kumar S', ' Venugopal', ' PURUSHOTHAMAN', ' Hari', ' Sl Prasanna', ' Sonia', ' Ramana Murthy', ' s bhargavi', ' Lakshman', ' Devi', ' jitendra sai', ' Ram', ' vakada ramana', ' Ravindra Pamidi', ' Praveen', ' Sai Stylish', ' MADHU', ' Uma Chavali', ' TEJARAM THRI', ' Jagan', ' Rakesh Power', ' Maheshwari', ' RAMACHANDRA RAO', ' Jaswanth', ' Srikanth', ' Akshay Kumar', ' swamy m', ' lalitha dhulipala', ' Vision Properties', ' Honey Group', ' New Living Properties', ' podilapu simhachalam', ' Dinakar']
['FloorGround out of 4', 'FloorGround out of 4', 'Floor4 out of 4', 'Floor14 out of 15', 'Floor2 out of 4', 'Floor1 out of 4', 'Floor3 out of 5', 'Basement out of 17', 'Floor3 out of 14', 'Floor2 out of 10', 'FloorGround out of 7', 'Floor16 out of 16', 'FloorGround out of 5', 'Floor1 out of 7', 'Floor2 out of 4', 'Floor2 out of 5', 'Floor3 out of 6', 'Floor1 out of 7', 'Floor1 out of 4', 'Floor6 out of 12', 'Floor9 out of 9', 'Floor1 out of 4', 'Floor2 out of 4', 'Floor5 out of 5', 'Floor2 out of 4', 'Floor1 out of 3', 'Floor13 out of 27', 'Floor5 out of 13', 'Floor3 out of 3', 'FloorGround out of 4', 'Floor8 out of 9', 'Floor1 out of 5', 'Floor5 out of 15', 'Floor4 out of 7', 'FloorGround out of 76', 'Floor4 out of 4', 'FloorGround out of 3', 'Floor1 out of 6', 'Floor5 out of 20', 'Floor6 out of 12', 'Floor7 out of 7', 'FloorGround out of 4', 'Floor1 out of 3', 'Floor21 out of 21', 'Floor3 out of 3', 'Floor7 out of 21', 'Floor5 out of 7', 'Floor5 out of 7', 'Floor4 out of 15', 'Floor9 out of 15', 'Floor17 out of 18', 'Floor5 out of 12', 'Floor7 out of 7', 'Floor15 out of 23', 'Floor3 out of 4', 'Floor2 out of 13', 'Floor2 out of 4', 'Floor1 out of 11', 'Floor1 out of 4', 'Floor1 out of 2', 'FloorGround out of 2', 'Floor2 out of 2', 'Floor1 out of 2', 'Floor1 out of 2', 'Floor1 out of 2', 'Floor4 out of 4', 'Floor3 out of 5', 'Floor16 out of 16', 'Floor3 out of 4', 'Floor1 out of 2', 'Floor4 out of 4', 'Floor3 out of 4', 'Floor1 out of 2', 'Floor2 out of 4', 'Floor2 out of 2', 'Floor2 out of 3', 'Floor2 out of 3', 'Floor1 out of 4', 'Floor1 out of 3', 'Floor1 out of 3', 'Floor1 out of 1', 'FloorGround out of 2', 'Floor1 out of 2', 'Floor1 out of 1', 'Floor1 out of 2', 'Floor1 out of 1', 'Floor1 out of 4', 'Floor1 out of 4', 'Floor2 out of 5', 'Floor10 out of 16', 'Floor15 out of 16', 'FloorGround out of 6', 'Floor2 out of 3', 'Floor3 out of 5', 'Floor4 out of 4', 'Floor1 out of 5', 'Floor2 out of 4', 'Floor2 out of 5', 'Floor2 out of 5', 'Basement out of 3', 'Floor2 out of 5', 'Floor3 out of 5', 'Floor1 out of 5', 'Floor2 out of 5', 'Floor1 out of 5', 'Floor5 out of 5', 'Floor1 out of 5', 'Floor2 out of 4', 'Floor2 out of 10', 'Floor4 out of 5', 'Floor2 out of 3', 'Floor1 out of 5', 'Floor4 out of 5', 'Floor2 out of 5', 'Floor1 out of 5', 'Floor3 out of 5', 'Floor5 out of 5', 'Floor3 out of 5', nan, nan]
[' Kattigenahalli', ' Ayodaya Nagar', ' Electronic City ', ' Tumkur Road ', ' Kudlu Gate ', ' Hal Stage 2', ' Murugeshpalya', ' Begur Road ', ' Judicial Layout', ' Bellandur', ' Kasturi Nagar ', ' Koramangala Block 1 ', ' Sarjapur Road ', ' Devanahalli ', ' Hanumantha Nagar', ' ', ' Doddakannelli ', ' Electronic City ', ' Sarjapur Road ', ' Jigani ', ' ', ' ', ' Jaya Nagar Block 3 ', ' whitefield ', ' whitefield ', ' Harlur ', ' Sarjapur Road ', ' Hoodi', ' Haralur Ma', ' Yelahanka ', ' Daulat Nagar ', ' Samel Pada ', ' Borivali West ', ' Goregaon West ', ' Vasai East ', ' Worli ', ' Kurla East ', ' Andheri East ', ' Kandivali East ', ' Mahim West ', ' Borivali West ', ' Chembur West ', ' ', ' ', ' Dadar West ', ' Boisar West ', ' Mira Road ', ' K', ' Virar West ', ' Vasai West ', ' Bhandup West ', ' Kalyan ', ' Goregaon East ', ' Marol Maroshi Road ', ' Malad West ', ' Vikhroli East ', ' Juhu ', ' Andheri East ', ' Jogeshwari West ', ' Mulund West ', ' Mannivakkam Chennai', ' New Perungalathur Chennai', ' Kovilambakkam Chennai', ' Perumbakkam Chennai', ' Mogappair Chennai', ' Tambaram West Tambaram Chennai', ' Manapakkam Chennai', ' Mogappair Chennai', ' Perumbakkam Chennai', ' Iyyappanthangal Chennai', ' Manapakkam Chennai', ' Madipakkam Chennai', ' Selaiyur Chennai', ' Velachery Chennai', ' Sithalapakkam Chennai', ' Adyar Chennai', ' Shankar Nagar Pammal Chennai', ' Chennai', ' Porur Chennai', ' Chennai', ' Villivakkam Chennai', ' Kundrathur Chennai', ' AGS Colony Velachery Chennai', ' Pallikaranai Chennai', ' Pozhichalur Chennai', ' Jothi Nagar Chitlapakkam Chennai', ' VGP Layout Palavakkam Chennai', ' Perundevi Ammal Nagar Chennai', ' Gu', ' Chennai', ' ', ' ', ' Madhurwada ', ' Pendurthi ', ' Pithapuram Colony ', ' Madhurwada ', ' Pendurthi ', ' Visalakshi Nagar ', ' Balaji Nagar ', ' Sujatha nagar ', ' ', ' Mural', ' Poth', ' Kurmannapalem ', ' Kurmannapalem ', ' Pendurthi ', ' Kurmannapalem ', ' ', ' ', ' Kancharapalem ', ' Kurmannapalem ', ' Railway New Colony ', ' Gajuwaka ', ' Aganampudi ', ' Madhurwada ', ' Tagarapuvalsa ', ' Parawada ', ' PM Palem ', ' Madhurwada ', ' MVP Colony ']
['bangalore', 'bangalore', 'bangalore', 'bangalore', 'bangalore', 'bangalore', 'bangalore', 'bangalore', 'bangalore', 'bangalore', 'bangalore', 'bangalore', 'bangalore', 'bangalore', 'bangalore', 'bangalore', 'bangalore', 'bangalore', 'bangalore', 'bangalore', 'bangalore', 'bangalore', 'bangalore', 'bangalore', 'bangalore', 'bangalore', 'bangalore', 'bangalore', 'bangalore', 'bangalore', 'mumbai', 'mumbai', 'mumbai', 'mumbai', 'mumbai', 'mumbai', 'mumbai', 'mumbai', 'mumbai', 'mumbai', 'mumbai', 'mumbai', 'mumbai', 'mumbai', 'mumbai', 'mumbai', 'mumbai', 'mumbai', 'mumbai', 'mumbai', 'mumbai', 'mumbai', 'mumbai', 'mumbai', 'mumbai', 'mumbai', 'mumbai', 'mumbai', 'mumbai', 'mumbai', 'chennai', 'chennai', 'chennai', 'chennai', 'chennai', 'chennai', 'chennai', 'chennai', 'chennai', 'chennai', 'chennai', 'chennai', 'chennai', 'chennai', 'chennai', 'chennai', 'chennai', 'chennai', 'chennai', 'chennai', 'chennai', 'chennai', 'chennai', 'chennai', 'chennai', 'chennai', 'chennai', 'chennai', 'chennai', 'chennai', 'visakhapatnam', 'visakhapatnam', 'visakhapatnam', 'visakhapatnam', 'visakhapatnam', 'visakhapatnam', 'visakhapatnam', 'visakhapatnam', 'visakhapatnam', 'visakhapatnam', 'visakhapatnam', 'visakhapatnam', 'visakhapatnam', 'visakhapatnam', 'visakhapatnam', 'visakhapatnam', 'visakhapatnam', 'visakhapatnam', 'visakhapatnam', 'visakhapatnam', 'visakhapatnam', 'visakhapatnam', 'visakhapatnam', 'visakhapatnam', 'visakhapatnam', 'visakhapatnam', 'visakhapatnam', 'visakhapatnam', 'visakhapatnam', 'visakhapatnam']
120
120
120
120
120
120
120
120

In [151]:
# inserting NaN's at index positions
per_sqt.insert(32,np.nan)
per_sqt.insert(39,np.nan)
per_sqt.insert(43,np.nan)
per_sqt.insert(60,np.nan)
per_sqt.insert(67,np.nan)
per_sqt.append(np.nan)
per_sqt.append(np.nan)
per_sqt.append(np.nan)
per_sqt.append(np.nan)
per_sqt.append(np.nan)

In [152]:
# inserting NaN's at index positions
Floor.append(np.nan)
Floor.append(np.nan)

In [153]:
# inserting NaN's at index positions
Carpet_Area.append(np.nan)

In [154]:
# Creation the Dict with cloumns names as strings and values as column names in which values are present.
df1 = {'City':City,
             'Area':Area,
             'Owner':Owner,
             'BHK':BHK,
             'Floor':Floor,
             'price':price,
             'Carpet_Area':Carpet_Area,
             'per_sqt':per_sqt
}

In [156]:
Project1 = pd.DataFrame(df1)

In [158]:
Project1.head(20)

,City,Area,Owner,BHK,Floor,price,Carpet_Area,per_sqt
0,bangalore,Kattigenahalli,Omkar Pandey,3,FloorGround out of 4,₹60 Lac,1000,₹4950
1,bangalore,Ayodaya Nagar,gokul,2,FloorGround out of 4,₹80 Lac,1150,₹6957
2,bangalore,Electronic City,Thayumanavan,2,Floor4 out of 4,₹48 Lac,1060,₹4528
3,bangalore,Tumkur Road,Prasanna,3,Floor14 out of 15,₹1.35 Cr,1790,₹7542
4,bangalore,Kudlu Gate,Akash Akash,2,Floor2 out of 4,₹61 Lac,803,₹5706
5,bangalore,Hal Stage 2,av nath,3,Floor1 out of 4,₹1.30 Cr,1640,₹7303
6,bangalore,Murugeshpalya,Sangeeta Pillai,2,Floor3 out of 5,₹50 Lac,1250,₹5000
7,bangalore,Begur Road,ganga k,3,Basement out of 17,₹1.80 Cr,1588,₹11335
8,bangalore,Judicial Layout,Anjan K,3,Floor3 out of 14,₹1 Cr,1000,₹8889
9,bangalore,Bellandur,Omesh Saraf,2,Floor2 out of 10,₹1.02 Cr,1465,₹6997
10,bangalore,Kasturi Nagar,Mohd Hussain,3,FloorGround out of 7,₹1.45 Cr,1500,₹8146
11,bangalore,Koramangala Block 1,Rahul Jain,3,Floor16 out of 16,₹3.85 Cr,1418,₹20632
12,bangalore,Sarjapur Road,Gaurav Kumar GAURAV,3,FloorGround out of 5,₹70 Lac,1350,₹5655
13,bangalore,Devanahalli,Ancy,2,Floor1 out of 7,₹85 Lac,1000,₹6071
14,bangalore,Hanumantha Nagar,Anoop,2,Floor2 out of 4,₹98 Lac,1250,₹9800
15,bangalore,,geetha,2,Floor2 out of 5,₹60 Lac,857,₹6367
16,bangalore,Doddakannelli,Omkar Omkar,2,Floor3 out of 6,₹78 Lac,753,₹5158
17,bangalore,Electronic City,ruchika,2,Floor1 out of 7,₹57 Lac,1186,₹6374
18,bangalore,Sarjapur Road,jeswanth,3,Floor1 out of 4,₹1.08 Cr,1250,₹4553
19,bangalore,Jigani,vikas saxena,3,Floor6 out of 12,₹57 Lac,770,₹4545

In [169]:
# conversion of DataFrame to csv
Project1.to_csv('DF1.csv')

In [160]:
# Code for the collection of the data
# here list of 3 cities are taken and collection of data is done for them
cities = ['ranchi','haridwar','vadodara']
price=[]
per_sqt=[]
BHK=[]
Carpet_Area=[]
Owner=[]
Floor=[]
Area=[]
City=[]
for j in cities:
    url = "https://www.magicbricks.com/flats-in-"+j+"-for-sale-pppfs"
    print(url)
    page = requests.get(url)
    soup = BeautifulSoup(page.text)
    
    for i in soup.find_all("div",class_="mb-srp__card__price--amount"):
        price.append(i.text)
        
    for i in soup.find_all("div",class_="mb-srp__card__price--size"):
        per_sqt.append(i.text.split(' ')[0])
        
    for i in soup.find_all("h2",class_="mb-srp__card--title"):
        BHK.append(i.text[0])
        
    for i in soup.find_all("div",class_="mb-srp__card__summary--value"):
        a =i.text
        b = re.findall(r"(\d+)\ssqft",str(a))
        if b:
            Carpet_Area.append(b[0])
    for i in soup.find_all('div',class_='mb-srp__card__ads--name'):
        Owner.append(i.text.split(':')[1])    

            
    for i in soup.find_all("div",class_="mb-srp__card__summary__list--item"):
        a = i.text
        b = re.findall(r"\w+\s\w+\s\w+\s\d+",a)
        if b:
            Floor.append(b[0])
            
    for i in soup.find_all("h2",class_="mb-srp__card--title"):
        Area.append(i.text.split('in')[1].split(',')[0])
        City.append(j)
    print(i,'---->', len(Owner))
    print(i,'---->', len(Floor))
    print(i,'---->', len(per_sqt))

https://www.magicbricks.com/flats-in-ranchi-for-sale-pppfs
<h2 class="mb-srp__card--title">3 BHK Flat for Sale in Hawai Nagar , Ranchi</h2> ----> 30
<h2 class="mb-srp__card--title">3 BHK Flat for Sale in Hawai Nagar , Ranchi</h2> ----> 30
<h2 class="mb-srp__card--title">3 BHK Flat for Sale in Hawai Nagar , Ranchi</h2> ----> 28
https://www.magicbricks.com/flats-in-haridwar-for-sale-pppfs
<h2 class="mb-srp__card--title">1 BHK Flat for Sale in Sidcul , Haridwar</h2> ----> 60
<h2 class="mb-srp__card--title">1 BHK Flat for Sale in Sidcul , Haridwar</h2> ----> 60
<h2 class="mb-srp__card--title">1 BHK Flat for Sale in Sidcul , Haridwar</h2> ----> 57
https://www.magicbricks.com/flats-in-vadodara-for-sale-pppfs
<h2 class="mb-srp__card--title">4 BHK Flat for Sale in , Vadodara</h2> ----> 90
<h2 class="mb-srp__card--title">4 BHK Flat for Sale in , Vadodara</h2> ----> 89
<h2 class="mb-srp__card--title">4 BHK Flat for Sale in , Vadodara</h2> ----> 83

In [163]:
# inserting NaN's at index positions
Floor.append(np.nan)
Carpet_Area.append(np.nan)

In [162]:
# inserting NaN's at index positions
per_sqt.insert(11,np.nan)
per_sqt.insert(25,np.nan)
per_sqt.insert(53,np.nan)
per_sqt.insert(71,np.nan)
per_sqt.insert(72,np.nan)
per_sqt.insert(79,np.nan)
per_sqt.insert(84,np.nan)

In [164]:
# printing to see the values are obtained are not
print(price)
print(per_sqt)
print(BHK)
print(Carpet_Area)
print(Owner)
print(Floor)
print(Area)
print(City)

# Finding the length to see is all the lengths are same
print(len(price))
print(len(per_sqt))
print(len(BHK))
print(len(Carpet_Area))
print(len(Owner))
print(len(Floor))
print(len(Area))
print(len(City))

['₹62 Lac ', '₹76.4 Lac ', '₹77 Lac ', '₹31.5 Lac ', '₹68.6 Lac ', '₹75 Lac ', '₹40 Lac ', '₹58 Lac ', '₹60 Lac ', '₹56 Lac ', '₹51 Lac ', '₹77 Lac ', '₹31 Lac ', '₹33 Lac ', '₹1.15 Cr ', '₹68 Lac ', '₹82 Lac ', '₹32 Lac ', '₹58 Lac ', '₹45 Lac ', '₹45 Lac ', '₹45 Lac ', '₹1.25 Cr ', '₹40 Lac ', '₹48 Lac ', '₹1.05 Cr ', '₹60 Lac ', '₹91 Lac ', '₹48 Lac ', '₹1.25 Cr ', '₹41 Lac ', '₹77 Lac ', '₹23.5 Lac ', '₹58 Lac ', '₹14.3 Lac ', '₹1.90 Cr ', '₹38 Lac ', '₹32 Lac ', '₹50.5 Lac ', '₹47 Lac ', '₹28 Lac ', '₹55 Lac ', '₹40 Lac ', '₹35 Lac ', '₹48 Lac ', '₹58 Lac ', '₹16.5 Lac ', '₹25 Lac ', '₹20 Lac ', '₹16 Lac ', '₹67 Lac ', '₹25 Lac ', '₹28 Lac ', '₹37 Lac ', '₹40 Lac ', '₹66 Lac ', '₹14 Lac ', '₹34 Lac ', '₹65 Lac ', '₹22 Lac ', '₹60 Lac ', '₹80 Lac ', '₹22 Lac ', '₹31 Lac ', '₹25 Lac ', '₹23 Lac ', '₹15.5 Lac ', '₹45 Lac ', '₹79 Lac ', '₹45 Lac ', '₹30 Lac ', '₹7.5 Lac ', '₹45 Lac ', '₹35 Lac ', '₹65 Lac ', '₹47 Lac ', '₹19.5 Lac ', '₹25 Lac ', '₹31 Lac ', '₹35 Lac ', '₹25 Lac ', '₹90 Lac ', '₹50 Lac ', '₹82 Lac ', '₹19 Lac ', '₹60 Lac ', '₹8 Lac ', '₹27 Lac ', '₹42 Lac ', '₹1.20 Cr ']
['₹4655', '₹4200', '₹5325', '₹5497', '₹4400', '₹3731', '₹3774', '₹4531', '₹4317', '₹3733', '₹3682', nan, '₹2897', '₹3986', '₹5476', '₹5207', '₹5325', '₹2712', '₹4629', '₹4110', '₹4039', '₹4274', '₹5556', '₹3448', '₹3840', nan, '₹4484', '₹5170', '₹4800', '₹8333', '₹2522', '₹4529', '₹2901', '₹5273', '₹2192', '₹5429', '₹3140', '₹2960', '₹3483', '₹3167', '₹2605', '₹3963', '₹3636', '₹3500', '₹3967', '₹4531', '₹3113', '₹3846', '₹2857', '₹2133', '₹4295', '₹3125', '₹3230', nan, '₹3687', '₹3667', '₹2318', '₹3716', '₹3824', '₹2933', '₹2953', '₹5333', '₹2444', '₹3875', '₹2941', '₹3286', '₹2053', '₹2970', '₹4158', '₹2093', '₹2542', nan, nan, '₹3182', '₹3683', '₹3298', '₹1696', '₹2551', '₹2818', nan, '₹2174', '₹3817', '₹5556', '₹3216', nan, '₹2521', '₹4000', '₹3000', '₹2545', '₹4615']
['3', '3', '3', '1', '3', '3', '2', '3', '3', '3', '3', '3', '2', '2', '3', '3', '3', '2', '2', '2', '2', '3', '4', '2', '3', '5', '3', '3', '2', '3', '2', '3', '2', '3', '1', '2', '3', '2', '2', '3', '2', '3', '2', '2', '3', '2', '1', '1', '1', '1', '4', '2', '1', '2', '2', '3', '1', '2', '3', '1', '3', '3', '2', '2', '2', '1', '1', '2', '3', '4', '2', '1', '2', '2', '3', '3', '2', '2', '2', '2', '2', '3', '3', '3', '2', '4', '1', '2', '3', '4']
['1110', '1500', '1150', '573', '1560', '2010', '930', '1280', '1250', '1500', '1385', '1212', '1000', '800', '1925', '1306', '1540', '1180', '971', '950', '1114', '1053', '2250', '950', '1150', '1650', '1338', '1760', '968', '1500', '1490', '750', '1100', '650', '3000', '1210', '719', '1450', '1484', '1075', '1388', '1025', '890', '1050', '500', '530', '650', '700', '650', '1600', '800', '867', '1450', '900', '1800', '604', '915', '1700', '750', '2032', '1500', '900', '780', '1208', '700', '755', '1515', '1900', '1465', '1080', '450', '1010', '850', '1016', '1025', '800', '980', '800', '640', '1150', '2358', '900', '2350', '750', '1580', '200', '600', '1650', '2600', nan]
[' Waseem Ahmad', ' Anuj Krchandra', ' Rabindra Bakshi', ' Abhishek Gupta', ' Shree Ram Developers', ' vivek chandra', ' sushant Bhattacharjee', ' Ritesh Nagpal', ' Nitin Kumar', ' PARTHO BOSE', ' Pradeep', ' rajesh singh', ' ashish singh', ' sanjeev', ' Kshav', ' Abhishek', ' Neeraj', ' Manit Kumar', ' Mukesh Mukesh', ' Samita Chatterjee', ' shakuntala verma', ' vikash singh', ' Avishek Modi Modi', ' Amar nath Pandey', ' MANISH KUMAR', ' taha', ' Rabish Kumar', ' Pintu Singh', ' Ravi Prasad', ' Rajiv Ranjan', ' Kiran Kumar Patel', ' SHREYA SAGAR', ' Krrish', ' Rajendra Wadhwa', ' Shakti Verma', ' Mridul Puri', ' Manish', ' Ajay', ' tarun agarwal', ' Arvind Bhardwaj', ' Jasjit Pannu', ' Abhishek Chauhan', ' sandeep', ' &quot;Magicbricks User&quot;', ' Dinesh Kukreti', ' Shalinirahal Banga', ' Alok Singh', ' saba b Khan', ' Rahul kumar', ' SANDEEP KUMAR', ' Sandeep Chaturvedi', ' AYUSH SAXENA', ' puneet', ' Abhishek chaudhary', ' Rishabh Kapoor', ' Surendra Satija', ' Harendra Kumar', ' chandra', ' Rohit', ' Dharmveer', ' Samy', ' Sudhanshu Kavthekar', ' Jaimin Parmar ', ' paresh', ' Mayur Patel', ' Parimal Patel', ' Rakesh', ' Bhavik Bhavik Mehta', ' Jyotsna Khoda', ' raghuvirsinh Vaghela', ' Pratik gosaliya', ' Umakant parmar', ' Akshat Dani', ' Nimisha', ' Hitansh Agrawal', ' anil', ' mitul patel', ' anil makvana', ' Manubhai Shah', ' Shashank', ' Pushpita Roy Choudhury', ' namita Namita', ' Deepak Singh', ' Manish Nagarajan', ' Ankur Javia', ' Jigar', ' Maheshbhai Dhokia', ' Aniruddha', ' Bindi shah', ' Jiten chokshi']
['Floor3 out of 4', 'Floor5 out of 6', 'Floor4 out of 4', 'Floor2 out of 4', 'Floor8 out of 12', 'Floor2 out of 4', 'Floor1 out of 4', 'Floor2 out of 7', 'Floor4 out of 4', 'Floor1 out of 1', 'Floor3 out of 4', 'Floor4 out of 6', 'Floor1 out of 4', 'Floor3 out of 3', 'Floor9 out of 10', 'Floor4 out of 4', 'Floor4 out of 5', 'Floor3 out of 4', 'FloorGround out of 6', 'Floor3 out of 4', 'Floor3 out of 3', 'Floor1 out of 11', 'Floor3 out of 4', 'Floor3 out of 3', 'Floor2 out of 3', 'FloorGround out of 8', 'Floor1 out of 4', 'Floor4 out of 4', 'Floor1 out of 4', 'Floor4 out of 8', 'FloorGround out of 4', 'FloorGround out of 7', 'Floor6 out of 8', 'Floor1 out of 5', 'Floor1 out of 4', 'FloorGround out of 2', 'Floor2 out of 7', 'Floor3 out of 7', 'Floor6 out of 6', 'Floor1 out of 1', 'Floor4 out of 6', 'Floor2 out of 5', 'FloorGround out of 4', 'Floor3 out of 7', 'Floor5 out of 7', 'FloorGround out of 1', 'FloorGround out of 3', 'FloorGround out of 4', 'Floor3 out of 4', 'Floor1 out of 4', 'Floor2 out of 4', 'Floor3 out of 3', 'Floor4 out of 4', 'Floor3 out of 3', 'Floor5 out of 12', 'Floor4 out of 5', 'Floor2 out of 2', 'Floor3 out of 7', 'Floor2 out of 7', 'Floor4 out of 6', 'Floor5 out of 5', 'Floor3 out of 4', 'Floor3 out of 4', 'Floor1 out of 3', 'Floor5 out of 5', 'Floor2 out of 4', 'Floor6 out of 8', 'Floor3 out of 4', 'Floor4 out of 5', 'Floor1 out of 5', 'Floor3 out of 4', 'Floor1 out of 3', 'Floor3 out of 5', 'Floor5 out of 12', 'Floor4 out of 9', 'Floor2 out of 5', 'Floor2 out of 8', 'Floor1 out of 3', 'Floor4 out of 5', 'Floor4 out of 4', 'Floor4 out of 9', 'Floor5 out of 5', 'Floor9 out of 9', 'Floor3 out of 4', 'Floor5 out of 5', 'Floor2 out of 4', 'Floor1 out of 5', 'Floor3 out of 5', 'Floor2 out of 2', nan]
[' H', ' ', ' S', ' Ratu Road ', ' Harihar S', ' Bariatu Road ', ' Morabadi ', ' Bahu Bazar ', ' ', ' Vikas Nagar ', ' Bariatu ', ' Hesag ', ' ', ' Barga', ' Sector 2 Masibari ', ' Upper Chutia ', ' Hazaribag Road ', ' Namkum ', ' Lalpur ', ' Hesag ', ' Kokar ', ' BIT Mesra ', ' ', ' Harihar S', ' H', ' ', ' Namkum ', ' ', ' Bariatu Road ', ' Hawai Nagar ', ' Sidcul ', ' Roshanabad ', ' Sidcul ', ' Devpura ', ' Laksar Road ', ' Arya Nagar ', ' Jwalapur ', ' Roshanabad ', ' Patanjali ', ' Rajaji National Park ', ' Roshanabad ', ' Jwalapur ', ' Jwalapur ', ' Jwalapur ', ' ', ' Roorkee ', ' Patanjali ', ' ', ' Shivalik Nagar ', ' Shantikunj ', ' Haripur Kalan ', ' ', ' Kankhal ', ' Jwalapur ', ' Patanjali ', ' NH-58 ', ' Jwalapur ', ' Sidcul ', ' NH-58 ', ' Sidcul ', ' Vasna Bhayli Ma', ' Race Course circle ', ' Ajwa Road ', ' ', ' Makar Pura ', ' Chhani ', ' Suryanagar ', ' Gotri Road Gotri ', ' Vasant Vihar ', ' Sevasi ', ' Chhani ', ' Nani Bapod ', ' Race Course circle ', ' Kalali ', ' Sama Savli Road ', ' Gorwa ', ' Bill ', ' Vasna Bhayli Ma', ' Subhanpura ', ' Bhayli ', ' Danteshwar ', ' Vasna Bhayli Ma', ' Gotri Sevasi Road ', ' Harni Road ', ' Sayajipura ', ' Bill ', ' ', ' Vasna Bhayli Ma', ' ', ' ']
['ranchi', 'ranchi', 'ranchi', 'ranchi', 'ranchi', 'ranchi', 'ranchi', 'ranchi', 'ranchi', 'ranchi', 'ranchi', 'ranchi', 'ranchi', 'ranchi', 'ranchi', 'ranchi', 'ranchi', 'ranchi', 'ranchi', 'ranchi', 'ranchi', 'ranchi', 'ranchi', 'ranchi', 'ranchi', 'ranchi', 'ranchi', 'ranchi', 'ranchi', 'ranchi', 'haridwar', 'haridwar', 'haridwar', 'haridwar', 'haridwar', 'haridwar', 'haridwar', 'haridwar', 'haridwar', 'haridwar', 'haridwar', 'haridwar', 'haridwar', 'haridwar', 'haridwar', 'haridwar', 'haridwar', 'haridwar', 'haridwar', 'haridwar', 'haridwar', 'haridwar', 'haridwar', 'haridwar', 'haridwar', 'haridwar', 'haridwar', 'haridwar', 'haridwar', 'haridwar', 'vadodara', 'vadodara', 'vadodara', 'vadodara', 'vadodara', 'vadodara', 'vadodara', 'vadodara', 'vadodara', 'vadodara', 'vadodara', 'vadodara', 'vadodara', 'vadodara', 'vadodara', 'vadodara', 'vadodara', 'vadodara', 'vadodara', 'vadodara', 'vadodara', 'vadodara', 'vadodara', 'vadodara', 'vadodara', 'vadodara', 'vadodara', 'vadodara', 'vadodara', 'vadodara']
90
90
90
90
90
90
90
90

In [165]:
# Creation the Dict with cloumns names as strings and values as column names in which values are present.
df2 = {'City':City,
             'Area':Area,
             'Owner':Owner,
             'BHK':BHK,
             'Floor':Floor,
             'price':price,
             'Carpet_Area':Carpet_Area,
             'per_sqt':per_sqt
}

In [166]:
# Creation of DataFrame
Project2=pd.DataFrame(df2)

In [172]:
Project2.head(20)

,City,Area,Owner,BHK,Floor,price,Carpet_Area,per_sqt
0,ranchi,H,Waseem Ahmad,3,Floor3 out of 4,₹62 Lac,1110,₹4655
1,ranchi,,Anuj Krchandra,3,Floor5 out of 6,₹76.4 Lac,1500,₹4200
2,ranchi,S,Rabindra Bakshi,3,Floor4 out of 4,₹77 Lac,1150,₹5325
3,ranchi,Ratu Road,Abhishek Gupta,1,Floor2 out of 4,₹31.5 Lac,573,₹5497
4,ranchi,Harihar S,Shree Ram Developers,3,Floor8 out of 12,₹68.6 Lac,1560,₹4400
5,ranchi,Bariatu Road,vivek chandra,3,Floor2 out of 4,₹75 Lac,2010,₹3731
6,ranchi,Morabadi,sushant Bhattacharjee,2,Floor1 out of 4,₹40 Lac,930,₹3774
7,ranchi,Bahu Bazar,Ritesh Nagpal,3,Floor2 out of 7,₹58 Lac,1280,₹4531
8,ranchi,,Nitin Kumar,3,Floor4 out of 4,₹60 Lac,1250,₹4317
9,ranchi,Vikas Nagar,PARTHO BOSE,3,Floor1 out of 1,₹56 Lac,1500,₹3733
10,ranchi,Bariatu,Pradeep,3,Floor3 out of 4,₹51 Lac,1385,₹3682
11,ranchi,Hesag,rajesh singh,3,Floor4 out of 6,₹77 Lac,1212,NaN
12,ranchi,,ashish singh,2,Floor1 out of 4,₹31 Lac,1000,₹2897
13,ranchi,Barga,sanjeev,2,Floor3 out of 3,₹33 Lac,800,₹3986
14,ranchi,Sector 2 Masibari,Kshav,3,Floor9 out of 10,₹1.15 Cr,1925,₹5476
15,ranchi,Upper Chutia,Abhishek,3,Floor4 out of 4,₹68 Lac,1306,₹5207
16,ranchi,Hazaribag Road,Neeraj,3,Floor4 out of 5,₹82 Lac,1540,₹5325
17,ranchi,Namkum,Manit Kumar,2,Floor3 out of 4,₹32 Lac,1180,₹2712
18,ranchi,Lalpur,Mukesh Mukesh,2,FloorGround out of 6,₹58 Lac,971,₹4629
19,ranchi,Hesag,Samita Chatterjee,2,Floor3 out of 4,₹45 Lac,950,₹4110

In [168]:
# conversion of DataFrame to csv
Project2.to_csv('DF2.csv')

In [179]:
# Code for the collection of the data
# here list of 7 cities are taken and collection of data is done for them
cities = ['greater-noida','gurgaon','mangalore','raipur','agra','bhiwadi','mysore']
City = []
Area=[]
Owner=[]
BHK=[]
Floor=[]
price=[]
Carpet_Area=[]
per_sqt=[]
for j in cities:
    url = "https://www.magicbricks.com/flats-in-"+j+"-for-sale-pppfs"
    print(url)
    page = requests.get(url)
    soup = BeautifulSoup(page.text)
    
    for i in soup.find_all("div",class_="mb-srp__card__price--amount"):
        price.append(i.text)
        
    for i in soup.find_all("div",class_="mb-srp__card__price--size"):
        per_sqt.append(i.text.split(' ')[0])
        
    for i in soup.find_all("h2",class_="mb-srp__card--title"):
        BHK.append(i.text[0])
        
    for i in soup.find_all("div",class_="mb-srp__card__summary--value"):
        a =i.text
        b = re.findall(r"(\d+)\ssqft",str(a))
        if b:
            Carpet_Area.append(b[0])
    for i in soup.find_all('div',class_='mb-srp__card__ads--name'):
        Owner.append(i.text.split(':')[1])    

            
    for i in soup.find_all("div",class_="mb-srp__card__summary__list--item"):
        a = i.text
        b = re.findall(r"\w+\s\w+\s\w+\s\d+",a)
        if b:
            Floor.append(b[0])
            
    for i in soup.find_all("h2",class_="mb-srp__card--title"):
        Area.append(i.text.split('in')[1].split(',')[0])
        City.append(j)
    print(i,'---->', len(Owner))
    print(i,'---->', len(Floor))
    print(i,'---->', len(per_sqt))

https://www.magicbricks.com/flats-in-greater-noida-for-sale-pppfs
<h2 class="mb-srp__card--title">3 BHK Flat for Sale in Yamuna Expressway , Greater Noida</h2> ----> 29
<h2 class="mb-srp__card--title">3 BHK Flat for Sale in Yamuna Expressway , Greater Noida</h2> ----> 31
<h2 class="mb-srp__card--title">3 BHK Flat for Sale in Yamuna Expressway , Greater Noida</h2> ----> 28
https://www.magicbricks.com/flats-in-gurgaon-for-sale-pppfs
<h2 class="mb-srp__card--title">3 BHK Flat for Sale in Sector 65 , Gurgaon</h2> ----> 59
<h2 class="mb-srp__card--title">3 BHK Flat for Sale in Sector 65 , Gurgaon</h2> ----> 64
<h2 class="mb-srp__card--title">3 BHK Flat for Sale in Sector 65 , Gurgaon</h2> ----> 56
https://www.magicbricks.com/flats-in-mangalore-for-sale-pppfs
<h2 class="mb-srp__card--title">2 BHK Flat for Sale in Yeyyadi Indl. Estate , Mangalore</h2> ----> 89
<h2 class="mb-srp__card--title">2 BHK Flat for Sale in Yeyyadi Indl. Estate , Mangalore</h2> ----> 93
<h2 class="mb-srp__card--title">2 BHK Flat for Sale in Yeyyadi Indl. Estate , Mangalore</h2> ----> 82
https://www.magicbricks.com/flats-in-raipur-for-sale-pppfs
<h2 class="mb-srp__card--title">2 BHK Flat for Sale in Daldal Seoni , Raipur</h2> ----> 119
<h2 class="mb-srp__card--title">2 BHK Flat for Sale in Daldal Seoni , Raipur</h2> ----> 123
<h2 class="mb-srp__card--title">2 BHK Flat for Sale in Daldal Seoni , Raipur</h2> ----> 112
https://www.magicbricks.com/flats-in-agra-for-sale-pppfs
<h2 class="mb-srp__card--title">3 BHK Flat for Sale in Rakabganj , Agra</h2> ----> 149
<h2 class="mb-srp__card--title">3 BHK Flat for Sale in Rakabganj , Agra</h2> ----> 153
<h2 class="mb-srp__card--title">3 BHK Flat for Sale in Rakabganj , Agra</h2> ----> 142
https://www.magicbricks.com/flats-in-bhiwadi-for-sale-pppfs
<h2 class="mb-srp__card--title">2 BHK Flat for Sale in Alwar Bypass Road , Bhiwadi</h2> ----> 179
<h2 class="mb-srp__card--title">2 BHK Flat for Sale in Alwar Bypass Road , Bhiwadi</h2> ----> 184
<h2 class="mb-srp__card--title">2 BHK Flat for Sale in Alwar Bypass Road , Bhiwadi</h2> ----> 172
https://www.magicbricks.com/flats-in-mysore-for-sale-pppfs
<h2 class="mb-srp__card--title">2 BHK Flat for Sale in Sriramapura , Mysore</h2> ----> 209
<h2 class="mb-srp__card--title">2 BHK Flat for Sale in Sriramapura , Mysore</h2> ----> 213
<h2 class="mb-srp__card--title">2 BHK Flat for Sale in Sriramapura , Mysore</h2> ----> 198

In [184]:
# printing to see the values are obtained are not
print(City)
print(Area)
print(BHK)
print(Carpet_Area)
print(Owner)
print(price)
print(per_sqt)
print(Floor)

# Finding the length to see is all the lengths are same
print(len(City))
print(len(Area))
print(len(BHK))
print(len(Carpet_Area))
print(len(Owner))
print(len(price))
print(len(per_sqt))
print(len(Floor))

['greater-noida', 'greater-noida', 'greater-noida', 'greater-noida', 'greater-noida', 'greater-noida', 'greater-noida', 'greater-noida', 'greater-noida', 'greater-noida', 'greater-noida', 'greater-noida', 'greater-noida', 'greater-noida', 'greater-noida', 'greater-noida', 'greater-noida', 'greater-noida', 'greater-noida', 'greater-noida', 'greater-noida', 'greater-noida', 'greater-noida', 'greater-noida', 'greater-noida', 'greater-noida', 'greater-noida', 'greater-noida', 'greater-noida', 'greater-noida', 'gurgaon', 'gurgaon', 'gurgaon', 'gurgaon', 'gurgaon', 'gurgaon', 'gurgaon', 'gurgaon', 'gurgaon', 'gurgaon', 'gurgaon', 'gurgaon', 'gurgaon', 'gurgaon', 'gurgaon', 'gurgaon', 'gurgaon', 'gurgaon', 'gurgaon', 'gurgaon', 'gurgaon', 'gurgaon', 'gurgaon', 'gurgaon', 'gurgaon', 'gurgaon', 'gurgaon', 'gurgaon', 'gurgaon', 'gurgaon', 'mangalore', 'mangalore', 'mangalore', 'mangalore', 'mangalore', 'mangalore', 'mangalore', 'mangalore', 'mangalore', 'mangalore', 'mangalore', 'mangalore', 'mangalore', 'mangalore', 'mangalore', 'mangalore', 'mangalore', 'mangalore', 'mangalore', 'mangalore', 'mangalore', 'mangalore', 'mangalore', 'mangalore', 'mangalore', 'mangalore', 'mangalore', 'mangalore', 'mangalore', 'mangalore', 'raipur', 'raipur', 'raipur', 'raipur', 'raipur', 'raipur', 'raipur', 'raipur', 'raipur', 'raipur', 'raipur', 'raipur', 'raipur', 'raipur', 'raipur', 'raipur', 'raipur', 'raipur', 'raipur', 'raipur', 'raipur', 'raipur', 'raipur', 'raipur', 'raipur', 'raipur', 'raipur', 'raipur', 'raipur', 'raipur', 'agra', 'agra', 'agra', 'agra', 'agra', 'agra', 'agra', 'agra', 'agra', 'agra', 'agra', 'agra', 'agra', 'agra', 'agra', 'agra', 'agra', 'agra', 'agra', 'agra', 'agra', 'agra', 'agra', 'agra', 'agra', 'agra', 'agra', 'agra', 'agra', 'agra', 'bhiwadi', 'bhiwadi', 'bhiwadi', 'bhiwadi', 'bhiwadi', 'bhiwadi', 'bhiwadi', 'bhiwadi', 'bhiwadi', 'bhiwadi', 'bhiwadi', 'bhiwadi', 'bhiwadi', 'bhiwadi', 'bhiwadi', 'bhiwadi', 'bhiwadi', 'bhiwadi', 'bhiwadi', 'bhiwadi', 'bhiwadi', 'bhiwadi', 'bhiwadi', 'bhiwadi', 'bhiwadi', 'bhiwadi', 'bhiwadi', 'bhiwadi', 'bhiwadi', 'bhiwadi', 'mysore', 'mysore', 'mysore', 'mysore', 'mysore', 'mysore', 'mysore', 'mysore', 'mysore', 'mysore', 'mysore', 'mysore', 'mysore', 'mysore', 'mysore', 'mysore', 'mysore', 'mysore', 'mysore', 'mysore', 'mysore', 'mysore', 'mysore', 'mysore', 'mysore', 'mysore', 'mysore', 'mysore', 'mysore', 'mysore']
[' Zeta 1 ', ' Sector P4 ', ' Eta 2', ' Sector 3 ', ' Zeta 1 ', ' Omicron ', ' Greater Noida West ', ' Eta 2', ' Yamuna Expressway ', ' Greater Noida West ', ' ', ' Chi 5 ', ' Jaypee Greens ', ' Zeta 1 ', ' Greater Noida West ', ' Omicron 1 ', ' Greater Noida West ', ' Sector 1 Greater Noida West ', ' Greater Noida West ', ' Greater Noida West ', ' Greater Noida West ', ' ', ' Noida Extention ', ' Sector 1 Greater Noida West ', ' Omicron 3 ', ' UPSIDC Site C Block H ', ' Sector 16 ', ' Chi 5 ', ' Yamuna Expressway ', ' Yamuna Expressway ', ' Jal Vayu Vihar', ' Sohna Sector 32 ', ' Kendriya Vihar', ' Sector 23 ', ' Sohna Sector 35 ', ' Sector 84 ', ' Sector 104 ', ' Sector 78 ', ' Sector 112 ', ' Sector 102 ', ' Sector 48 ', ' Sector 7 ', ' Sector 55 ', ' DLF City Phase 1 ', ' Sector 57 ', ' New Colony', ' Sohna Sector 33 ', ' Sector 83 ', ' Sector 47 ', ' Sector 37C', ' Sector 9 ', ' DLF City Phase 1 ', ' Sector 4 ', ' South City 2', ' New Palam Vihar', ' Sector 54 ', ' Patel Nagar', ' Sector 77', ' Sector 65 ', ' Sector 65 ', ' Shakti Nagar ', ' Urwa ', ' Bunts Hostel Road ', ' Urwa ', ' Kulshekar ', ' Kulai ', ' Bajpe ', ' Ujire ', ' Bondel ', ' Kateel ', ' K', ' Shakti Nagar ', ' Falnir ', ' Kulai ', ' Kadri ', ' Padil ', ' Kulai ', ' Urwa ', ' Falnir ', ' Jepp', ' Derebail ', ' Mulky ', ' ', ' Pandeshwar ', ' Ashok Nagar ', ' Konchady Cross Road ', ' Pumpwell ', ' Mukka ', ' Nandigudda ', ' Yeyyadi Indl. Estate ', ' Daldal Seoni ', ' Mowa ', ' Avanti Vihar ', ' Shankar Nagar ', ' Santoshi Nagar ', ' Naya Raipur ', ' Hirapur Road ', ' VIP Road ', ' Mathpurena ', ' Boria Kalan ', ' Amlidhi ', ' Bhatagaon ', ' Kabir Nagar ', ' Shankar Nagar ', ' Hirapur Road ', ' NH 6 ', ' Shankar Nagar ', ' Deopuri ', ' Kota ', ' Amlidhi ', ' Hirapur Road ', ' Santoshi Nagar ', ' Boria Kalan ', ' Shankar Nagar ', ' Amleshwar ', ' Amlidhi ', ' Kachna Road ', ' Mowa ', ' Amanaka ', ' Daldal Seoni ', ' Sikandra ', ' Vibhav Nagar ', ' Vijay Nagar Colony ', ' Civil L', ' Dayal Bagh ', ' Civil L', ' Shastri Puram ', ' Agra Shamshabad Raja Kherah Marg ', ' Dayal Bagh ', ' Dayal Bagh ', ' Dayal Bagh ', ' Fatehabad Road ', ' Agra Shamshabad Raja Kherah Marg ', ' Sikandra ', ' Sikandra ', ' Dayal Bagh ', ' Sikandra ', ' Fatehabad Road ', ' Shastri Puram ', ' Shastri Puram ', ' Fatehabad Road ', ' Sikandra ', ' Shahganj ', ' Fatehabad Road ', ' Gwalior Road ', ' Agra Shamshabad Raja Kherah Marg ', ' Sector 16B Awas Vikas Colony ', ' Fatehabad Road ', ' Shastri Puram ', ' Rakabganj ', ' Alwar Bypass Road ', ' ', ' Alwar Bypass Road ', ' Alwar Bypass Road ', ' Alwar Bypass Road ', ' Alwar Bypass Road ', ' Alwar Bypass Road ', ' Alwar Bypass Road ', ' Alwar Bypass Road ', ' Alwar Bypass Road ', ' Alwar Bypass Road ', ' Bhiwadi Mod ', ' Tapukara ', ' Alwar Bhiwadi Road ', ' Vasundhara Nagar ', ' Alwar Bypass Road ', ' Alwar Bypass Road ', ' Alwar Bypass Road ', ' Alwar Bypass Road ', ' Alwar Bypass Road ', ' Alwar Bypass Road ', ' Alwar Bypass Road ', ' Alwar Bypass Road ', ' Rampura ', ' Alwar Bypass Road ', ' Alwar Bypass Road ', ' Vasundhara Nagar ', ' Tapukara ', ' Alwar Bypass Road ', ' Alwar Bypass Road ', ' Gokulam ', ' Bogadi ', ' JP Nagar ', ' Yadavgiri ', ' Yadavgiri ', ' Hebbal ', ' Vijayanagar 4th Stage ', ' Bogadi ', ' Sharadadevi Nagar ', ' Alanahalli ', ' Vijaynagar 3rd Stage ', ' Belagola ', ' ', ' Visveshwara Nagar ', ' ', ' Siddhartha Layout ', ' Vidyarayanapuram ', ' Srirangapatnam ', ' JP Nagar ', ' Bogadi ', ' Chamarajapura ', ' Metagalli ', ' Jaya Laxmi Puram ', ' Hebbal 2nd Stage ', ' Lakshmipuram ', ' ', ' Kuvempunagar ', ' ', ' V V Mohalla ', ' Sriramapura ']
['2', '3', '3', '2', '2', '3', '4', '2', '1', '2', '2', '4', '4', '4', '2', '2', '3', '2', '3', '2', '2', '2', '3', '2', '3', '2', '3', '3', '2', '3', '2', '3', '3', '2', '1', '3', '2', '3', '3', '4', '3', '3', '3', '4', '3', '3', '2', '3', '3', '2', '4', '2', '4', '4', '2', '3', '3', '4', '3', '3', '2', '2', '3', '2', '3', '2', '4', ' ', '3', '2', '1', '2', '3', '2', '2', '3', '3', '2', '2', '2', '2', '2', '2', '2', '3', '2', '3', '2', '3', '2', '2', '3', '3', '2', '3', '2', '3', '2', '2', '2', '2', '2', '1', '2', '2', '3', '2', '3', '3', '2', '3', '3', '3', '3', '3', '2', '3', '2', '1', '2', '2', '3', '2', '2', '5', '2', '2', '3', '3', '3', '3', '2', '2', '2', '2', '3', '5', '3', '2', '2', '3', '3', '2', '3', '2', '2', '2', '3', '2', '3', '2', '2', '2', '1', '2', '2', '2', '2', '1', '1', '3', '1', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '3', '3', '2', '1', '2', '3', '4', '2', '2', '2', '1', '2', '3', '4', '2', '2', '4', '2', '2', '2', '2', '3', '3', '3', '3', '2', '3', '3', '2', '3', '2', '2', '2', '2', '2']
['1200', '1120', '995', '970', '895', '1775', '2364', '660', nan, '950', '995', '3210', '3441', '2200', '910', '840', '1530', '862', '1055', '615', '1155', '950', '840', '870', '1395', '1115', '1285', '1494', '1115', '13750', '900', '1789', '1500', '750', '310', '1750', '570', '1657', '3763', '1800', '1300', '900', '1950', '1556', '1217', nan, '610', '1745', '2470', '10372', '1450', '1250', '1550', '1800', '550', '3650', '960', '1500', '1500', '3069', '670', '1100', '1700', '1275', '1330', '906', '3030', nan, '1390', '1260', '660', '1166', '3900', '975', '1390', '1070', '1870', '1040', '1000', '1320', '783', '72', '1000', '1330', '1356', '884', '1613', '1100', '1341', '1200', '970', '1200', '1985', '840', '1250', '943', '799', '900', '1050', '487', '700', '815', '505', '866', '721', '1200', '1030', '1500', '1805', '1230', '965', '1250', '1337', '960', '1200', '1000', '1500', '860', '550', '906', '900', '1540', '1250', '850', nan, '1050', '848', '1350', '1050', '1400', nan, '1192', '1115', '1000', '660', '1675', '2410', nan, '862', '1250', '1400', '1800', '1750', '1675', '960', '940', '1425', '926', '861', '1500', '1165', '555', '980', '466', '1234', '750', '780', '650', '630', '600', '1430', '660', '815', '1250', '1170', '1111', '1000', '1150', '829', '700', '950', '1250', '1150', '599', '750', '1590', '1522', '500', '630', '790', '1650', '1487', '1095', '9', '1280', '400', '1400', '1174', '650', '1050', '890', '2000', '911', '1280', '800', '1095', '1553', '1875', '1681', '1400', '1019', '2200', '1380', '1100', '1650', '1070', '1080', '1200', '900', '1115']
[' RAHUL TRIVEDI', ' R Bhattacharjee', ' Ashutosh', ' Sandeep gautam', ' vijay', ' PRASAD', ' Kamal Bansal', ' Avik Dey', ' Harkesh Sharma', ' Bhagat Singh', ' Mangat Rai', ' AN SINHA', ' Nihit', ' Shiv Kumar', ' Right Value Solutions', ' Adhunik Propmart', ' Homes And Desire', ' Investors Lab', ' Vardhman Reality', ' piyush nair', ' A Plus Associates', ' Bricksnwall Innovations Pvt.Ltd.', ' Pragati ', ' Prof Arora', ' Prabhat Sharma', ' Gaurav', ' sanjeev', ' Mohd Sarfaraz', ' Atif', ' Sandeep Jain', ' Mohit', ' Nithin Abraham', ' Arun Yadav', ' Lionel Richie', ' Shubham Solanki', ' Anshul', ' Ajay Sharma', ' Pushpendra Sethi', ' Y S Dwivedi', ' Rahul Arora', ' Devesh', ' RAHUL', ' Kapur', ' sanjay kaushik', ' Naresh', ' Rahul', ' Karun', ' Gurdeep Singh', ' Pradeep Sharma', ' Ravinder Chauhan', ' Axiom Landbase Pvt. Ltd.', ' Jk Batra', ' sunil yadav', ' Rishabh Arora', ' Pankaj Ahlawat', ' VIVEK SHARMA', ' Real Estate Gurgaon', ' Akhilesh Sharma ', ' Ankush', ' Manjunath S', ' Govinda', ' Varun Nayak', ' Jeanson Veigas', ' Chethan', ' Naveen Kamath', ' Devdhar Shetty', ' Gopal', ' Stany', ' Brahmari Vilas', ' Baptist Dcunha', ' Priya', ' Iqbal ', ' Santosh Babu Salian', ' Hassan', ' Rajesh Antony Fernandes', ' jaysen', ' Govinda Sharma', ' hashura', ' Lance', ' Arwin', ' sharath kumar', ' Sameer', ' Sabeena Farhath', ' Suman Kumar', ' pkumar', " James D'SA", ' roshan', ' Sunil Veigas', ' SNEHA', ' D Suryaprakash', ' Bhumika Bansal', ' carlus', ' Vaibhav Shukla', ' Khushboo Kashyap', ' Deekaha', ' Divya Singh', ' Arpit Jain', ' Mahesh', ' geeta shrivastava', ' ajit singh', ' Prem Pvt Ltd', ' vijay', ' Siddharth Buildcon', ' Kusum kumari', ' Priyesh Gupta', ' Devinder Singh', ' womesh womesh', ' sandip Agarwal', ' Chainika', ' Karnjeet Biswas', ' TEJESHWARI SAHU', ' Mitchell', ' Angad Lalwani', ' achyutananda', ' Manoj mati', ' vidyadhar behra', ' Sumit Wadhwani', ' Saurabh upadhyay', ' Shubham Soni', ' Vikas Gulati', ' vishal sharma', ' Arnav Singh', ' Vinod Kumar', ' Deepika Chahar', ' Shikha', ' Shubham Kumar', ' hemant sharma', ' Prem lal Taneja', ' Yatendra kumar mehrotra', ' Umang Mathur', ' Akshit Rajoriya', ' Sanjeev Singh', ' nitin singh', ' ajay kumar', ' Divya pandey', ' GALAXY PRINT PACK', ' SHWETANG SHARMA', ' PRAVEEN KUMAR', ' Sapna', ' Ganpati World', ' Shrey Shankar', ' Rakesh Agarwal ', ' Sanchit gupta', ' PRASHANT', ' adil hussain', ' Mohini Sharma', ' vivek jain', ' VIMAL TIWARI', ' Dr Archika Gupta Dr Archika', ' Amit Kumar Saini', ' Radha Kanha', ' M K Realtech', ' R K Real Estate', ' Vikram', ' Amita Singh', ' Raj Singh', ' Dharm Chauhan', ' Sunil Kumar', ' vineet', ' Sandeep singh', ' Ashok Sood', ' munish', ' Brahmprakash', ' Satish', ' Sachinrajput', ' Sunil Kumar', ' Shailender', ' Sumit Kumar', ' Rahul Rijhwani', ' darshan kumar', ' Chandresh', ' Rahul Chauhan', ' Narendra Kumar Agarwal', ' Vivek Anand Semwal', ' Vibhu', ' SANCHITA', ' kuldeep tomer', ' Parveen khanna', ' Pardeep N/A ', ' Vijay', ' Ravi Nambiar', ' Pick Your Prop Estates LLP', ' Veena', ' Amar Kumar Prasad', ' Jagadeesha', ' Meghana', ' Shashi', ' Satish Krishna', ' ARUN', ' subbareddy subbareddy', ' Mallesh', ' Karthik', ' Nanda', ' Mohammed Mansoor', ' Shriya Mankani', ' Nataraj D M', ' Narasimha murthy', ' Vijay Menon', ' Prakash', ' G S ANANTHA', ' Gowrish Bhaskar', ' Ramachandra Murthy', ' Thulaseedharan pillai A', ' Rathan', ' sheelavathi', ' Nayana A.S', ' Srikanth', ' MANJUNATHA', ' Chakko', nan]
['₹47.5 Lac ', '₹46 Lac ', '₹37 Lac ', '₹24 Lac ', '₹48 Lac ', '₹65.4 Lac ', '₹1 Cr ', '₹27 Lac ', '₹15 Lac ', '₹35 Lac ', '₹65 Lac ', '₹2.10 Cr ', '₹3.31 Cr ', '₹98 Lac ', '₹43.5 Lac ', '₹48.5 Lac ', '₹80 Lac ', '₹61.2 Lac ', '₹56 Lac ', '₹50.5 Lac ', '₹63 Lac ', '₹25.5 Lac ', '₹68.9 Lac ', '₹23 Lac ', '₹55 Lac ', '₹44 Lac ', '₹51 Lac ', '₹65 Lac ', '₹33 Lac ', '₹50 Lac ', '₹80 Lac ', '₹1.80 Cr ', '₹1.50 Cr ', '₹45 Lac ', '₹17 Lac ', '₹93 Lac ', '₹35 Lac ', '₹81.1 Lac ', '₹4.60 Cr ', '₹2.60 Cr ', '₹1.20 Cr ', '₹54 Lac ', '₹1.40 Cr ', '₹1.85 Cr ', '₹99 Lac ', '₹85 Lac ', '₹42 Lac ', '₹1 Cr ', '₹3.50 Cr ', '₹93 Lac ', '₹1.20 Cr ', '₹1.32 Cr ', '₹1.60 Cr ', '₹2.35 Cr ', '₹28 Lac ', '₹10.90 Cr ', '₹46 Lac ', '₹1.50 Cr ', '₹2.28 Cr ', '₹5 Cr ', '₹22 Lac ', '₹79 Lac ', '₹69.5 Lac ', '₹58 Lac ', '₹54.8 Lac ', '₹65 Lac ', '₹2 Cr ', '₹10.1 Lac ', '₹65 Lac ', '₹35 Lac ', '₹19 Lac ', '₹40 Lac ', '₹1.80 Cr ', '₹65 Lac ', '₹75 Lac ', '₹48.5 Lac ', '₹90 Lac ', '₹79 Lac ', '₹65 Lac ', '₹50 Lac ', '₹60 Lac ', '₹35 Lac ', '₹32 Lac ', '₹75 Lac ', '₹1.01 Cr ', '₹40 Lac ', '₹1.20 Cr ', '₹45 Lac ', '₹68.5 Lac ', '₹48 Lac ', '₹25 Lac ', '₹77 Lac ', '₹68 Lac ', '₹52 Lac ', '₹29.1 Lac ', '₹31.8 Lac ', '₹32.5 Lac ', '₹30 Lac ', '₹42 Lac ', '₹7.5 Lac ', '₹23 Lac ', '₹31.5 Lac ', '₹14 Lac ', '₹35 Lac ', '₹25 Lac ', '₹33 Lac ', '₹30 Lac ', '₹33.3 Lac ', '₹1.35 Cr ', '₹49 Lac ', '₹30 Lac ', '₹29.1 Lac ', '₹33 Lac ', '₹43.4 Lac ', '₹25 Lac ', '₹36 Lac ', '₹42.9 Lac ', '₹20 Lac ', '₹12.5 Lac ', '₹25 Lac ', '₹25.5 Lac ', '₹43.5 Lac ', '₹68 Lac ', '₹35 Lac ', '₹1.35 Cr ', '₹65 Lac ', '₹44.4 Lac ', '₹33.5 Lac ', '₹42 Lac ', '₹48 Lac ', '₹47 Lac ', '₹40.5 Lac ', '₹28 Lac ', '₹35 Lac ', '₹17.5 Lac ', '₹60 Lac ', '₹81.9 Lac ', '₹55 Lac ', '₹40 Lac ', '₹42 Lac ', '₹44 Lac ', '₹65 Lac ', '₹59.9 Lac ', '₹51 Lac ', '₹24 Lac ', '₹44 Lac ', '₹65 Lac ', '₹24 Lac ', '₹41.3 Lac ', '₹90 Lac ', '₹38 Lac ', '₹12 Lac ', '₹23 Lac ', '₹13 Lac ', '₹36 Lac ', '₹18 Lac ', '₹23 Lac ', '₹13.5 Lac ', '₹11 Lac ', '₹16.8 Lac ', '₹37 Lac ', '₹28 Lac ', '₹15 Lac ', '₹18.8 Lac ', '₹28 Lac ', '₹17.9 Lac ', '₹19 Lac ', '₹27 Lac ', '₹32.5 Lac ', '₹14.5 Lac ', '₹21 Lac ', '₹30 Lac ', '₹22 Lac ', '₹20 Lac ', '₹20 Lac ', '₹59 Lac ', '₹50 Lac ', '₹10 Lac ', '₹18 Lac ', '₹30 Lac ', '₹80 Lac ', '₹60 Lac ', '₹45 Lac ', '₹68 Lac ', '₹95 Lac ', '₹58 Lac ', '₹82 Lac ', '₹58 Lac ', '₹50 Lac ', '₹85 Lac ', '₹58 Lac ', '₹1.01 Cr ', '₹60 Lac ', '₹56 Lac ', '₹48 Lac ', '₹65.7 Lac ', '₹60 Lac ', '₹75 Lac ', '₹75 Lac ', '₹70 Lac ', '₹52 Lac ', '₹1.45 Cr ', '₹85 Lac ', '₹1.63 Cr ', '₹80 Lac ', '₹40 Lac ', '₹69 Lac ', '₹60 Lac ', '₹60 Lac ', '₹72 Lac ']
['₹3958', '₹3286', nan, '₹3719', '₹2474', '₹5363', nan, '₹4230', '₹4091', '₹4805', '₹3684', '₹6533', '₹6542', '₹9001', '₹3912', '₹4780', '₹4663', '₹5229', '₹5322', '₹5308', '₹4630', '₹5020', '₹2429', '₹4700', '₹2370', '₹3943', '₹3946', '₹4351', '₹2960', '₹3636', '₹8889', '₹10061', nan, '₹5294', '₹3864', '₹4439', '₹5000', '₹4894', '₹12224', '₹9630', '₹8000', '₹5143', '₹7179', '₹11889', '₹8135', '₹8213', '₹4421', '₹5731', '₹14170', '₹6503', '₹7500', '₹9429', '₹7111', '₹11190', '₹3733', '₹25952', '₹4182', '₹7692', '₹12473', nan, '₹3284', '₹6371', '₹3971', '₹4549', '₹3487', nan, '₹5882', nan, '₹4676', '₹3070', '₹2879', nan, '₹4615', '₹6667', '₹5396', '₹4533', '₹4813', '₹6371', '₹6500', '₹3788', '₹5911', '₹3507', '₹3200', '₹5639', '₹5913', '₹4525', '₹6366', '₹3750', nan, '₹3491', '₹2577', '₹4968', '₹3426', '₹6190', '₹2327', '₹3372', '₹3368', '₹3333', '₹4000', '₹1540', '₹2706', '₹3099', '₹2772', '₹3000', '₹3467', '₹2538', '₹2913', '₹1852', '₹7479', '₹3984', '₹3109', '₹2327', '₹3143', '₹3600', '₹2778', '₹3600', '₹2860', '₹2326', '₹2273', '₹2759', '₹2833', '₹2753', '₹5440', '₹3097', '₹4500000', '₹6190', '₹3589', '₹2481', '₹4000', '₹3000', '₹4695', '₹3400', '₹2511', '₹3167', '₹2500', '₹3582', '₹3997', '₹2555', '₹3200', '₹3359', '₹2627', '₹3611', '₹3328', '₹3045', '₹2264', '₹3745', '₹4561', '₹2592', '₹3944', '₹6000', '₹4077', '₹1846', '₹1941', '₹2167', '₹2917', '₹2118', '₹2244', '₹2077', '₹1746', '₹2585', '₹2587', '₹4242', '₹1840', '₹1500', '₹2393', '₹1611', '₹1900', '₹2348', '₹2790', '₹1503', '₹2211', '₹2400', '₹1913', '₹2367', '₹2667', '₹3711', '₹3285', '₹1818', '₹2857', '₹3797', '₹3509', '₹4110', '₹7556', '₹6611', nan, '₹4296', '₹5857', '₹4940', '₹4762', '₹6071', '₹5115', '₹4208', '₹6586', '₹4375', '₹3863', '₹4000', nan, nan, '₹4462', '₹5000', '₹5103', '₹6591', '₹5743', '₹14818', '₹4848', '₹6389', '₹5000', nan, '₹6667', '₹6457']

In [181]:
# inserting NaN's at index positions
Owner.append(np.nan)

In [182]:
# inserting NaN's at index positions
Carpet_Area.insert(8,np.nan)
Carpet_Area.insert(45,np.nan)
Carpet_Area.insert(67,np.nan)
Carpet_Area.insert(124,np.nan)
Carpet_Area.insert(130,np.nan)
Carpet_Area.insert(137,np.nan)

In [183]:
# inserting NaN's at index positions
per_sqt.insert(5,np.nan)
per_sqt.insert(2,np.nan)
per_sqt.insert(32,np.nan)
per_sqt.insert(59,np.nan)
per_sqt.insert(65,np.nan)
per_sqt.insert(67,np.nan)
per_sqt.insert(71,np.nan)
per_sqt.insert(88,np.nan)
per_sqt.insert(184,np.nan)
per_sqt.insert(196,np.nan)
per_sqt.insert(197,np.nan)
per_sqt.insert(207,np.nan)

In [185]:
# Creation the Dict with cloumns names as strings and values as column names in which values are present.
df3 = {'City':City,
             'Area':Area,
             'Owner':Owner,
             'BHK':BHK,
             'Floor':Floor[0:210],
             'price':price,
             'Carpet_Area':Carpet_Area,
             'per_sqt':per_sqt
}

In [186]:
# creation of DataFrame
Project3=pd.DataFrame(df3)

In [187]:
Project3

,City,Area,Owner,BHK,Floor,price,Carpet_Area,per_sqt
0,greater-noida,Zeta 1,RAHUL TRIVEDI,2,Floor17 out of 22,₹47.5 Lac,1200,₹3958
1,greater-noida,Sector P4,R Bhattacharjee,3,Floor7 out of 9,₹46 Lac,1120,₹3286
2,greater-noida,Eta 2,Ashutosh,3,Floor8 out of 25,₹37 Lac,995,NaN
3,greater-noida,Sector 3,Sandeep gautam,2,Floor1 out of 2,₹24 Lac,970,₹3719
4,greater-noida,Zeta 1,vijay,2,Floor8 out of 16,₹48 Lac,895,₹2474
...,...,...,...,...,...,...,...,...
205,mysore,,Nayana A.S,2,FloorGround out of 3,₹40 Lac,1070,₹6389
206,mysore,Kuvempunagar,Srikanth,2,Floor1 out of 3,₹69 Lac,1080,₹5000
207,mysore,,MANJUNATHA,2,FloorGround out of 2,₹60 Lac,1200,NaN
208,mysore,V V Mohalla,Chakko,2,FloorGround out of 5,₹60 Lac,900,₹6667
209,mysore,Sriramapura,NaN,2,Floor1 out of 3,₹72 Lac,1115,₹6457

In [188]:
# conversion of DataFrame to csv
Project3.to_csv('DF3.csv')

In [189]:
# DataFrame concatenation into the final DF
FINALPROJECT = pd.concat([Project1,Project2,Project3])

In [190]:
# Resetting the index numbers after formaton of the finam DF
FINALPROJECT = FINALPROJECT.reset_index()

In [191]:
# Final uncleaned DataFrame
FINALPROJECT

,index,City,Area,Owner,BHK,Floor,price,Carpet_Area,per_sqt
0,0,bangalore,Kattigenahalli,Omkar Pandey,3,FloorGround out of 4,₹60 Lac,1000,₹4950
1,1,bangalore,Ayodaya Nagar,gokul,2,FloorGround out of 4,₹80 Lac,1150,₹6957
2,2,bangalore,Electronic City,Thayumanavan,2,Floor4 out of 4,₹48 Lac,1060,₹4528
3,3,bangalore,Tumkur Road,Prasanna,3,Floor14 out of 15,₹1.35 Cr,1790,₹7542
4,4,bangalore,Kudlu Gate,Akash Akash,2,Floor2 out of 4,₹61 Lac,803,₹5706
...,...,...,...,...,...,...,...,...,...
415,205,mysore,,Nayana A.S,2,FloorGround out of 3,₹40 Lac,1070,₹6389
416,206,mysore,Kuvempunagar,Srikanth,2,Floor1 out of 3,₹69 Lac,1080,₹5000
417,207,mysore,,MANJUNATHA,2,FloorGround out of 2,₹60 Lac,1200,NaN
418,208,mysore,V V Mohalla,Chakko,2,FloorGround out of 5,₹60 Lac,900,₹6667
419,209,mysore,Sriramapura,NaN,2,Floor1 out of 3,₹72 Lac,1115,₹6457

In [192]:
# final scraped data ---> uncleaned
FINALPROJECT.to_csv('Magicbrics_uncleaned.csv')